# Generated by Django 5.0.1 on 2026-01-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='stock_produ_tenant__e0d1a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='stock_produ_tenant__645cfb_idx',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_type',
            field=models.CharField(choices=[('EXENTA', 'Exenta (0%)'), ('5', 'Gravada 5%'), ('10', 'Gravada 10%')], default='10', help_text='Tipo de IVA aplicado', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, help_text='Precio de venta con IVA incluido', max_digits=10),
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='track_inventory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesale_price',
        ),
    ]
