# Generated by Django 5.0.1 on 2026-01-16 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('stock', '0002_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=0, help_text='Precio con IVA incluido', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_type',
            field=models.CharField(choices=[('EXENTA', 'Exenta (0%)'), ('5', 'Gravada 5%'), ('10', 'Gravada 10%')], default='10', help_text='Tipo de IVA', max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterModelTable(
            name='product',
            table='stock_product',
        ),
    ]
