# Generated by Django 5.0.1 on 2026-01-16 16:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('stock', '0003_add_tenant_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(default=uuid.UUID('d77d5c53-f954-481f-afa5-0ef19ca35e78'), on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(default=uuid.UUID('d77d5c53-f954-481f-afa5-0ef19ca35e78'), on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='tenant',
            field=models.ForeignKey(default=uuid.UUID('d77d5c53-f954-481f-afa5-0ef19ca35e78'), on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
    ]
