# Generated by Django 5.0.1 on 2026-02-11 16:30

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_exchangerate_options_and_more'),
        ('customers', '0005_customeraccount_installment_number_and_more'),
        ('quotes', '0001_initial'),
        ('stock', '0005_alter_category_tenant_alter_product_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Pedido')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('order_date', models.DateField(verbose_name='Fecha Pedido')),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega Esperada')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En Proceso'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total General')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer', verbose_name='Cliente')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='quotes.quote', verbose_name='Presupuesto Origen')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Unitario (c/IVA)')),
                ('tax_type', models.CharField(choices=[('EXENTA', 'Exenta (0%)'), ('5', 'Gravada 5%'), ('10', 'Gravada 10%')], default='10', max_length=10, verbose_name='Tipo IVA')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='IVA %')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Base imponible')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total (c/IVA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
                'ordering': ['id'],
            },
        ),
    ]
