# Generated by Django 5.0.1 on 2026-02-10 18:38

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_exchangerate_options_and_more'),
        ('customers', '0005_customeraccount_installment_number_and_more'),
        ('stock', '0005_alter_category_tenant_alter_product_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Presupuesto')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('issue_date', models.DateField(verbose_name='Fecha Emisión')),
                ('valid_until', models.DateField(verbose_name='Válido Hasta')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviado'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('expired', 'Vencido')], default='draft', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal')),
                ('total_tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total General')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('converted_to_order', models.BooleanField(default=False, verbose_name='Convertido a Pedido')),
                ('converted_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Conversión')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='customers.customer', verbose_name='Cliente')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio de venta con IVA incluido; se puede ajustar manualmente.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio Unitario (c/IVA)')),
                ('tax_type', models.CharField(choices=[('EXENTA', 'Exenta (0%)'), ('5', 'Gravada 5%'), ('10', 'Gravada 10%')], default='10', max_length=10, verbose_name='Tipo IVA')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='IVA %')),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Base imponible')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Monto IVA')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total (c/IVA)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product', verbose_name='Producto')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quote', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Item de Presupuesto',
                'verbose_name_plural': 'Items de Presupuesto',
                'ordering': ['id'],
            },
        ),
    ]
