# Generated by Django 5.0.1 on 2026-01-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dv',
            field=models.CharField(blank=True, help_text='Dígito Verificador', max_length=2, null=True, verbose_name='DV'),
        ),
        migrations.AddField(
            model_name='customer',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Nombre legal para facturación (si es empresa)', max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='customer',
            name='requires_invoice',
            field=models.BooleanField(default=False, help_text='Cliente solicita factura con RUC', verbose_name='Requiere Factura Legal'),
        ),
        migrations.AddField(
            model_name='customer',
            name='ruc',
            field=models.CharField(blank=True, help_text='Registro Único del Contribuyente', max_length=20, null=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('retail', 'Retail/Minorista'), ('wholesale', 'Wholesale/Mayorista')], default='retail', max_length=20),
        ),
    ]
