# Generated by Django 5.0.1 on 2026-01-27 16:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_exchangerate_options_and_more'),
        ('customers', '0002_customer_dv_customer_razon_social_and_more'),
        ('sales', '0004_cashregister'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('sale', 'Venta a Crédito'), ('payment', 'Pago'), ('adjustment', 'Ajuste')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='N° de recibo, comprobante, etc', max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transactions', to='customers.customer')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.sale')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
