# Generated by Django 5.0.1 on 2026-01-27 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customeraccount'),
        ('sales', '0004_cashregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='promised_date',
            field=models.DateField(blank=True, help_text='Fecha prometida de pago por el cliente', null=True),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='due_date',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento original', null=True),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
        ),
    ]
