# Generated by Django 5.0.1 on 2026-01-27 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customeraccount_promised_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='installment_number',
            field=models.IntegerField(default=1, help_text='Número de esta cuota (1, 2, 3...)'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, help_text='Transacción padre si esta es una cuota', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='customers.customeraccount'),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='total_installments',
            field=models.IntegerField(default=1, help_text='Número total de cuotas'),
        ),
    ]
