# Generated by Django 5.0.1 on 2026-01-19 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_exchangerate_options_and_more'),
        ('customers', '0002_customer_dv_customer_razon_social_and_more'),
        ('sales', '0002_alter_sale_options_alter_saleitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='currency_paid',
            field=models.CharField(choices=[('PYG', 'Guaraníes (₲)'), ('USD', 'Dólares ($)'), ('BRL', 'Reales (R$)')], default='PYG', help_text='Moneda en la que pagó el cliente', max_length=3, verbose_name='Moneda de Pago'),
        ),
        migrations.AddField(
            model_name='sale',
            name='exchange_rate_brl',
            field=models.DecimalField(decimal_places=2, default=1450, help_text='1 BRL = X PYG al momento de la venta', max_digits=10, verbose_name='Tasa BRL'),
        ),
        migrations.AddField(
            model_name='sale',
            name='exchange_rate_usd',
            field=models.DecimalField(decimal_places=2, default=7300, help_text='1 USD = X PYG al momento de la venta', max_digits=10, verbose_name='Tasa USD'),
        ),
        migrations.AddField(
            model_name='sale',
            name='paid_amount_original',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto en la moneda que pagó el cliente', max_digits=12, verbose_name='Monto Original'),
        ),
        migrations.AddField(
            model_name='sale',
            name='pix_reference',
            field=models.CharField(blank=True, help_text='ID de transacción PIX', max_length=100, verbose_name='Referencia PIX'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='change_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Vuelto (PYG)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Monto convertido a guaraníes', max_digits=12, verbose_name='Monto Pagado (PYG)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta Débito/Crédito'), ('pix', 'PIX'), ('transfer', 'Transferencia Bancaria'), ('credit', 'Fiado/Crédito'), ('mixed', 'Pago Mixto')], default='cash', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'currency_paid'], name='sales_sale_tenant__45c856_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'payment_method'], name='sales_sale_tenant__77e463_idx'),
        ),
    ]
