# Generated by Django 5.0.1 on 2026-01-22 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_exchangerate_options_and_more'),
        ('sales', '0003_sale_currency_paid_sale_exchange_rate_brl_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('initial_amount_pyg', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('initial_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('initial_amount_brl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_amount_pyg', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('expected_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expected_amount_brl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_amount_pyg', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('actual_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_amount_brl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('difference_pyg', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('difference_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('difference_brl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Abierta'), ('closed', 'Cerrada')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers_opened', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
    ]
