# Generated by Django 5.0.1 on 2026-02-03 19:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_exchangerate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre/Razón Social')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='RUC/CNPJ/CPF')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('payment_terms_days', models.IntegerField(default=30, help_text='Días de plazo para pagar (ej: 30, 60, 90)', verbose_name='Plazo de pago (días)')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Límite de crédito')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Persona de contacto')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Compra a Crédito'), ('payment', 'Pago a Proveedor'), ('adjustment', 'Ajuste')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('total_installments', models.IntegerField(default=1, verbose_name='Total de cuotas')),
                ('installment_number', models.IntegerField(default=1, verbose_name='Número de cuota')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('bank_transfer', 'Transferencia Bancaria'), ('check', 'Cheque'), ('pix', 'PIX'), ('card', 'Tarjeta')], max_length=20, verbose_name='Método de pago')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Nº Factura')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('parent_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='suppliers.supplieraccount', verbose_name='Transacción padre')),
                ('related_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='suppliers.supplieraccount', verbose_name='Compra relacionada')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier', verbose_name='Proveedor')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name': 'Cuenta de Proveedor',
                'verbose_name_plural': 'Cuentas de Proveedores',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tenant', 'name'], name='suppliers_s_tenant__566edc_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tenant', 'is_active'], name='suppliers_s_tenant__14ad59_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieraccount',
            index=models.Index(fields=['tenant', 'supplier'], name='suppliers_s_tenant__1a4c33_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieraccount',
            index=models.Index(fields=['tenant', 'transaction_type'], name='suppliers_s_tenant__d2e18a_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieraccount',
            index=models.Index(fields=['due_date'], name='suppliers_s_due_dat_5afc1f_idx'),
        ),
    ]
