# Generated by Django 5.0.1 on 2026-02-03 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_exchangerate_options_and_more'),
        ('stock', '0005_alter_category_tenant_alter_product_tenant_and_more'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item de Compra',
                'verbose_name_plural': 'Items de Compra',
                'ordering': ['product__name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='supplieraccount',
            name='suppliers_s_due_dat_5afc1f_idx',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterField(
            model_name='supplieraccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='supplieraccount',
            name='installment_number',
            field=models.IntegerField(default=1, help_text='0 = transacción padre, >0 = cuota activa', verbose_name='Número de cuota'),
        ),
        migrations.AlterField(
            model_name='supplieraccount',
            name='related_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to='suppliers.supplieraccount', verbose_name='Compra relacionada'),
        ),
        migrations.AlterField(
            model_name='supplieraccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado el'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('tenant', 'tax_id')},
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tenant', 'tax_id'], name='suppliers_s_tenant__dc1df9_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieraccount',
            index=models.Index(fields=['tenant', 'due_date'], name='suppliers_s_tenant__55c4cb_idx'),
        ),
        migrations.AddIndex(
            model_name='supplieraccount',
            index=models.Index(fields=['supplier', 'paid_date'], name='suppliers_s_supplie_c624d8_idx'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='stock.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(limit_choices_to={'transaction_type': 'purchase'}, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.supplieraccount', verbose_name='Compra'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
    ]
