# Generated by Django 5.0.1 on 2026-01-19 15:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'Dólar'), ('BRL', 'Real'), ('PYG', 'Guaraní')], max_length=3, unique=True)),
                ('rate_to_pyg', models.DecimalField(decimal_places=2, help_text='Tasa de conversión a Guaraníes', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tasa de Cambio',
                'verbose_name_plural': 'Tasas de Cambio',
            },
        ),
    ]
