# Generated by Django 5.0.1 on 2026-01-19 15:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exchangerate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ['currency'], 'verbose_name': 'Tasa de Cambio', 'verbose_name_plural': 'Tasas de Cambio'},
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency',
            field=models.CharField(choices=[('PYG', 'Guaraní paraguayo'), ('USD', 'Dólar estadounidense'), ('BRL', 'Real brasileño')], max_length=3, unique=True, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate_to_pyg',
            field=models.DecimalField(decimal_places=4, help_text='¿Cuántos guaraníes equivale 1 unidad de esta moneda?', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Tasa a Guaraníes'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
    ]
